In [ ]:
# latest update
# October 1st 2017
# Changes done by: Jimmy Vivas
# Added code description

# This code was developed by Jimmy Vivas

# The code will take all CSv files from a specific directory and process them at the same Time
# The program will need manual input to replace strings found for numeric data or null value
#   It will assign an integer value for each distinct string for each column (sensor)
# The code will generate as many csv files pero 1MM rows

# STEP 1 -. Update the path where the CSV files to be processed is located


### Create two folders
#### Folder 1 = CSVPAath1 is where the CSV file to be processed is located
#### Folder 2 = FinalPath is where all the files processed will be created

In [1]:
# Windows Path
CSVPath1 = '/Users/jvivas/Documents/Aspen/TJ/to be processed'
FinalPath = '/Users/jvivas/Documents/Aspen/TJ/processed'

# STEP 2-. Find characters in CSV file

In [2]:
from utils import *
pd.options.mode.chained_assignment = None  # default='warn'

In [3]:
CSVFileList = GetCSVList(CSVPath1)

CSVFile = CSVFileList[0]
CSVFileWithPath = CSVPath1 + "/" + CSVFileList[0]

csvFileSizeGB = GetFileSize(CSVFileWithPath)

In [4]:
df2 = LoadCSV(CSVFileWithPath, CSVFile)

Loading MTell-ESS12-2a-2017-2018-Revised-Split 1.csv

In [5]:
df2

,Tag,FICA4601AA,FICA4603AA,TICA4101AC,FICA4101AC,FICA4102AC,ISCA5501AA,A5601_CDE_FORC_COUTEAU
0,NaN,Flow from hydrocycl1 A4601 (Column 1) to tank ...,Flow from hydrocycl1 A4603 (Column 2) to tank ...,Temperature bicarb1ate from Column 1,Direct flow from Column 1 to tank A5001,Direct flow from Column 2 to tank A5001,Status of agitator in tank A5001,Forced moving of cleaner blade in centrifuge -...
1,12/1/17 0:00,3.084736347,3.603473663,67.42534637,23.58773804,23.35652351,1,Null
2,12/1/17 0:05,3.026164293,4.924383163,67.42534637,23.06841469,17.61572647,1,Null
3,12/1/17 0:10,15.01458836,2.967960119,67.42534637,25.68759727,21.5463829,1,Null
4,12/1/17 0:15,3.453973532,2.964725971,67.42534637,21.60227585,24.2540493,1,Null
5,12/1/17 0:20,3.30728364,2.961491823,67.42534637,24.5631218,25.62546349,1,Null
6,12/1/17 0:25,3.16059351,2.958257675,67.42534637,22.51179886,23.50535393,1,Null
7,12/1/17 0:30,3.048620224,2.955023766,67.42534637,21.5535202,22.42137527,1,Null
8,12/1/17 0:35,3.048620224,3.384344101,67.42534637,24.12174606,22.90222168,1,Null
9,12/1/17 0:40,3.048620224,5.220039368,67.42534637,25.73468208,18.14409828,1,Null
10,12/1/17 0:45,16.33917809,3.139779806,67.42534637,22.26660538,21.39020538,1,Null
11,12/1/17 0:50,3.88986969,3.032435656,67.42534637,19.94480896,22.76221085,1,Null
12,12/1/17 0:55,3.434397936,3.031501293,67.42534637,22.12729454,21.16107368,1,Null
13,12/1/17 1:00,3.333203077,3.030566931,67.42534637,23.06891251,20.54003525,1,Null
14,12/1/17 1:05,3.23200798,3.029632807,67.42534637,27.61014366,21.7646637,1,Null
15,12/1/17 1:10,3.130813122,3.568790436,67.42534637,22.46941185,22.6603775,1,Null
16,12/1/17 1:15,3.029618263,4.726733208,67.42534637,24.8103466,19.29540062,1,Null
17,12/1/17 1:20,15.39849186,2.95928216,67.42534637,22.38992882,23.19231606,1,Null
18,12/1/17 1:25,3.453616858,2.987125635,67.42534637,22.73557663,22.73348236,1,Null
19,12/1/17 1:30,3.379856586,3.014968872,67.42534637,19.68174744,21.22633553,1,Null
20,12/1/17 1:35,3.306096315,3.042812347,67.42534637,23.83187103,23.71687889,1,Null
21,12/1/17 1:40,3.232336044,3.070655823,67.42534637,23.25474358,24.30560303,1,Null
22,12/1/17 1:45,3.158575773,3.545633316,67.42534637,25.22725868,22.53618813,1,Null
23,12/1/17 1:50,3.084815502,4.953238487,67.42534637,23.23141098,17.87145042,1,Null
24,12/1/17 1:55,14.53030205,2.948223114,67.42534637,25.28202057,21.40610313,1,Null
25,12/1/17 2:00,3.616217852,2.946608543,67.42534637,19.97775459,22.50806236,1,Null
26,12/1/17 2:05,3.402055502,2.944994211,67.42534637,21.89504242,23.85977745,1,Null
27,12/1/17 2:10,3.301943541,2.943379641,67.42534637,23.00750351,26.54343033,1,Null
28,12/1/17 2:15,3.201831579,2.94176507,67.42534637,23.03270912,25.37059784,1,Null
29,12/1/17 2:20,3.101719618,3.355493546,67.42534637,27.19243813,22.59097099,1,Null
...,...,...,...,...,...,...,...,...
33655,3/27/18 21:30,0.444259644,2.703287125,33.13951111,0.172328949,27.00930405,1,0
33656,3/27/18 21:35,0.444259644,2.81896019,33.20341873,0.172328949,26.28548813,1,0
33657,3/27/18 21:40,0.444259644,2.934633255,33.26732254,0.172328949,27.40348244,1,0
33658,3/27/18 21:45,0.444259644,3.05030632,33.33122635,0.172328949,25.60187912,1,0
33659,3/27/18 21:50,0.444259644,3.165979385,33.39513397,0.172328949,26.61630249,1,0
33660,3/27/18 21:55,0.444259644,3.281652451,33.45903778,0.172328949,26.9614048,1,0
33661,3/27/18 22:00,0.444259644,11.57495499,33.5127182,0.172328949,22.81097603,1,0
33662,3/27/18 22:05,0.444259644,2.669051409,33.56534576,0.172328949,24.66771317,1,0
33663,3/27/18 22:10,0.444259644,2.743177891,33.61796951,0.172328949,24.55399895,1,0
33664,3/27/18 22:15,0.444259644,2.817304373,33.67059708,0.172328949,26.420187,1,0
33665,3/27/18 22:20,0.444259644,2.891430855,33.72322464,0.172328949,27.29813576,1,0
33666,3/27/18 22:25,0.444259644,2.965557337,33.7758522,0.172328949,25.82839203,1,0
33667,3/27/18 22:30,0.444259644,3.163105965,33.82847595,0.172328949,25.50764465,1,0
33668,3/27/18 22:35,0.444259644,11.2047472,33.88110352,0.172328949,26.49269104,1,0
33669,3/27/18 22:40,0.444259644,2.601283073,33.93373108,0.172328949,25.11660194,1,0
33670,3/27/18 22:45,0.444259644,2.686399698,33.98635864,0.172328949,25.77319908,1,0
33671,3/27/18 22:50,0.444259644,2.771516085,34.03743362,0.172328949,26.79136658,1,0
33672,3/27/18 22:55,0.444259644,2.85663271,34.087883,0.172328949,25.62391472,1,0
33673,3/27/18 23:00,0.444259644,2.969877005,34.13833618,0.172328949,26.91634369,1,0
33674,3/27/18 23:05,0.444259644,3.1868608,34.18878555,0.172328949,26.11386871,1,0
33675,3/27/18 23:10,0.444259644,12.2236433,34.23923492,0.172328949,25.46803284,1,0
33676,3/27/18 23:15,0.444259644,2.783106089,34.28968811,0.172328949,25.88804245,1,0
33677,3/27/18 23:20,0.444259644,2.871158123,34.34013748,0.172328949,26.76749802,1,0
33678,3/27/18 23:25,0.444259644,2.959209919,34.39058685,0.172328949,27.34213638,1,0
33679,3/27/18 23:30,0.444259644,3.047261715,34.44104004,0.172328949,24.29406548,1,0
33680,3/27/18 23:35,0.444259644,3.135313749,34.49148941,0.172328949,28.5985508,1,0
33681,3/27/18 23:40,0.444259644,3.223365545,34.54395676,0.172328949,26.41031075,1,0
33682,3/27/18 23:45,0.444259644,10.50049114,34.60076904,0.172328949,24.44773293,1,0
33683,3/27/18 23:50,0.444259644,2.737477303,34.65758133,0.172328949,26.87435341,1,0
33684,3/27/18 23:55,0.444259644,2.836446047,34.71439362,0.172328949,25.71786308,1,0

In [9]:
columns = df2.columns.tolist()

In [10]:
columns

['Tag',
 'FICA4601AA',
 'FICA4603AA',
 'TICA4101AC',
 'FICA4101AC',
 'FICA4102AC',
 'ISCA5501AA',
 'A5601_CDE_FORC_COUTEAU']

In [ ]:
CSVFileList = GetCSVList(CSVPath1)

CSVFile = CSVFileList[0]
CSVFileWithPath = CSVPath1 + "/" + CSVFileList[0]

csvFileSizeGB = GetFileSize(CSVFileWithPath)

if csvFileSizeGB > 1:
    StringListForAllSensors = SplitCSVFile_GetStrings(CSVFileWithPath, CSVFile)
    print ('These are all the strings found in the file: ' + str(StringListForAllSensors))
else:
    
    df2 = LoadCSV(CSVFileWithPath, CSVFile)
    
    # Rename date and time column
    print ('Renaming date and time column')
    RenameColumn(df2)
    # Apply Date and time format to dataframe
    print ('Applying date and time format')
    ApplyDateFormat(df2)
    
    # Apply Index and create two dataframes
    df2_1, df2_2 = SetIndex(df2)
    
    print ('Extracting strings from csv file')
    StringListForAllSensors = ExtractStrings(df2_1, df2_2)
    
    print ('These are all the strings found in the csv file: ' + str(StringListForAllSensors))

# Convert all strings to a Dictionary
StringListDict = {}.fromkeys(StringListForAllSensors, 'null')

# print ("# Run following line to see the list of Strings")
## Copy the result and paste it in the following line of code")
StringListDict

# STEP 3 - Replace null with Integers if necessary

In [ ]:
StringListDict = {'CLOSE': 'null',
 'NOT_OK': 'null',
 'NOT_OPEN': 'null',
 'Normal': 'null',
 'OFF': 'null',
 'RUN': 'null',
 'STOP': 'null'}

# STEP 4 -. Export processed files

In [ ]:
# Replacing known test to null
df2_2 = ReplaceStrings(df2_2, StringListDict)

# Create dataframe to export individual tags
df_final = pd.concat([df2_1, df2_2])

# Export Individual Tags to CSV
print("Creating CSV per TagName")
ExportTagNamesToCSV(df_final,FinalPath)

# Merge dataframes to export to CSV
mdf = FormatToPrevise(df2_1,df2_2)

# Check format data to be exported
# print(mdf.head(25))

# Export to CSV
print ('Creating CSVs to be imported into Aspen Mtell')
SplitPreviseFormatCSVFile(mdf,CSVFileList,FinalPath)

print("Done, check the processed folder")